### PR TITLE
Added Composer support and improved environment variable

### PR DESCRIPTION
**Pull request by Sebi94nbg**
- Added composer.json to support installations using Composer
- Updated README.md with information about Composer installation
- @psc-walch: I've tested and verified the composer.json [using my account](https://packagist.org/packages/paysafecard/paysafecard-rest_api-php). You may want to register your own account and repository at [Packagist.org](https://packagist.org/). Just let me know, when I shall/can delete this repository.
- A Webhook is required, in order to get automated updates from GitHub on Packagist: https://packagist.org/about#how-to-update-packages
- Please note, that you have to tag new releases in order, that they are available as newer version for Composer: https://github.com/paysafecard/paysafecard-rest_api-php/releases

### CODE REVIEW

**Comment by danadePSC** [comment]
@Sebi94nbg Can you please make this in a new repository and we will fork it to ours? We are reviewing the PHP samples codes and will pull new ones.

**Comment by Sebi94nbg** [comment]
@danadePSC all these changes are reflected in this fork: https://github.com/TS3Tools/paysafecard-rest_api-php

**Comment by danadePSC** [comment]
Hello @Sebi94nbg. I closed this PR and the other one because as I said we are already updating the sample codes and adding the composer. I left the "Issue" you opened, open :) We will update accordingly as soon as the new sample codes are ready. If you have further questions you can contact me at daniel.adelino@paysafe.com

**Comment by Sebi94nbg** [comment]
Thanks for your feedback!

Please let me know, when I can / shall delete the repository at [Packagist.org](https://packagist.org/packages/paysafecard/paysafecard-rest_api-php). :)

**Comment by Sebi94nbg** [comment]
Any news regarding composer support? When can we expect it, @danadePSC ?

**Pull request closed without merging**
